server:
  port: 6767
  ssl:
    certificate: classpath:ssl/dev/cert.pem
    certificate-private-key: classpath:ssl/dev/cert-key.pem

spring:
  application:
    name: wtu-web-backend
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://140.210.195.116:3306/wtu?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useUnicode=true
    username: root
    password: liuqi6602
    druid:
      max-active: 1000
      min-idle: 1
      keep-alive: true
      min-evictable-idle-time-millis: 600000
  task:
    execution:
      pool:
        core-size: 4
        max-size: 8
        queue-capacity: 1000
        keep-alive: 6000
      thread-name-prefix: wtu-web-backend-task-
  servlet:
    multipart:
      max-request-size: 10MB
      max-file-size: 10MB
      enabled: true
      file-size-threshold: 100B
  data:
    redis:
      host: 140.210.195.116
      port: 6379
      password: liuqi6602
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
          max-wait: 1000
      database: 0
  mail:
    host: smtp.163.com
    username: liuqi6602@163.com
    password: FYZZODKUFCEAVELS
    protocol: smtp
    default-encoding: UTF-8
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
      mail.smtp.ssl.enable: true
      mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
      mail.smtp.socketFactory.fallback: false
      mail.smtp.socketFactory.port: 465

  ############## Sa-Token 配置 (文档: https://sa-token.cc) ##############
sa-token:
  # token 名称（同时也是 cookie 名称）
  token-name: token
  # token 有效期（单位：秒） 默认30天，-1 代表永久有效
  timeout: -1
  # token 最低活跃频率（单位：秒），如果 token 超过此时间没有访问系统就会被冻结，默认-1 代表不限制，永不冻结
  active-timeout: -1
  # 是否允许同一账号多地同时登录 （为 true 时允许一起登录, 为 false 时新登录挤掉旧登录）
  is-concurrent: true
  # 在多人登录同一账号时，是否共用一个 token （为 true 时所有登录共用一个 token, 为 false 时每次登录新建一个 token）
  is-share: true
  # token 风格（默认可取值：uuid、simple-uuid、random-32、random-64、random-128、tik）
  token-style: uuid
  # 是否输出操作日志
  is-log: true

# springdoc-openapi项目配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs
  group-configs:
    - group: 'default'
      paths-to-match: '/**'
      packages-to-scan: com.xiaominfo.knife4j.demo.web
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/*.xml # 扫描resource下 mapper包里的所有xml文件
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

domain:
  frontend: https://localhost:67
  backend: https://localhost:6767
  name: localhost