server:
  ssl:
    certificate: classpath:ssl/pro/cert.pem
    certificate-private-key: classpath:ssl/pro/cert.key

netty:
  en:
    port: 3344
    root: /en
  cn:
    port: 4433
    root: /cn
  ssl:
    certificate: ssl/pro/netty.pem
    certificate-private-key: ssl/pro/netty.key

domain:
  frontend: https://warframe.team
  backend: https://warframe.team:6767
  name: warframe.team