server:
    port: 6767

spring:
    profiles:
        active: @spring.profiles.active@
    application:
        name: wtu-web-backend
    data:
        redis:
            database: 0
            host: 8.130.90.68
            port: 6379
            password: liuqi6602
            timeout: 10000
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 1
                    max-wait: -1
                    min-idle: 10
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://8.130.90.68:3306/wtu?characterEncoding=utf-8&serverTimezone=Asia/Shanghai&useUnicode=true
        username: root
        password: liuqi6602
        druid:
            max-active: 1000
            min-idle: 1
            keep-alive: true
            min-evictable-idle-time-millis: 600000
    task:
        execution:
            pool:
                core-size: 10
                max-size: 20
                queue-capacity: 100
                keep-alive: 1000
            thread-name-prefix: thread-
    servlet:
        multipart:
            max-request-size: 10MB
            max-file-size: 10MB
            enabled: true
            file-size-threshold: 100B
    mail:
        host: smtp.163.com
        username: liuqi6602@163.com
        password: FYZZODKUFCEAVELS
        protocol: smtp
        default-encoding: UTF-8
        properties:
            mail.smtp.auth: true
            mail.smtp.starttls.enable: true
            mail.smtp.starttls.required: true
            mail.smtp.ssl.enable: true
            mail.smtp.socketFactory.class: javax.net.ssl.SSLSocketFactory
            mail.smtp.socketFactory.fallback: false
            mail.smtp.socketFactory.port: 465


sa-token:
    token-name: token
    timeout: -1
    active-timeout: -1
    is-concurrent: true
    is-share: true
    token-style: uuid
    is-log: true

springdoc:
    swagger-ui:
        path: /swagger-ui.html
        tags-sorter: alpha
        operations-sorter: alpha
    api-docs:
        path: /v3/api-docs
    group-configs:
        group: 'default'
        paths-to-match: '/**'
        packages-to-scan: com.xiaominfo.knife4j.demo.web

knife4j:
    enable: true
    setting:
        language: zh_cn


mybatis-plus:
    mapper-locations: classpath:mapper/*.xml
    configuration:
        log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
        map-underscore-to-camel-case: true
